version: '3.1'
services:
  stats-server:
    build: stats/stats-server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore-with-me-stats
      - SPRING_DATASOURCE_USER=ivan
      - SPRING_DATASOURCE_PASSWORD=anypass


  stats-db:
    image: postgres:15-alpine
    container_name: stats-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explore-with-me-stats
      - POSTGRES_USER=ivan
      - POSTGRES_PASSWORD=anypass

  ewm-service:
    build: main
    image: main-image
    container_name: main-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explore-with-me-main
      - SPRING_DATASOURCE_USER=ivan
      - SPRING_DATASOURCE_PASSWORD=anypass

  ewm-db:
    image: postgres:15-alpine
    container_name: main-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=explore-with-me-main
      - POSTGRES_USER=ivan
      - POSTGRES_PASSWORD=anypass
