CREATE TABLE IF NOT EXISTS users (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS categories(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS locations(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
lat FLOAT NOT NULL,
lon FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS events(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
annotation VARCHAR(255) NOT NULL UNIQUE,
category_id BIGINT NOT NULL,
confirmed_request INTEGER,
created_on TIMESTAMP WITHOUT TIME ZONE,
description VARCHAR(255),
event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
initiator_id BIGINT NOT NULL,
locations_id BIGINT NOT NULL,
paid BOOLEAN NOT NULL,
participant_limit INTEGER,
published_on TIMESTAMP WITHOUT TIME ZONE,
request_moderation BOOLEAN,
state VARCHAR(255),
title VARCHAR(255) NOT NULL,
views BIGINT,
FOREIGN KEY (category_id) REFERENCES categories(id),
FOREIGN KEY (initiator_id) REFERENCES users(id),
FOREIGN KEY (locations_id) REFERENCES locations(id)
);

CREATE TABLE IF NOT EXISTS compilations(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
pinned BOOLEAN NOT NULL,
title VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS compilations_events(
compilation_id BIGINT PRIMARY KEY,
event_id BIGINT PRIMARY KEY,
FOREIGN KEY (compilation_id) REFERENCES compilations(id),
FOREIGN KEY (event_id) REFERENCES events(id)
);

CREATE TABLE IF NOT EXISTS participation_request(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
event_id BIGINT NOT NULL,
requester_id BIGINT NOT NULL,
status VARCHAR(255),
FOREIGN KEY (event_id) REFERENCES events(id),
FOREIGN KEY (requester_id) REFERENCES users(id)
);